Integration Test for ActionRepository
maksontakson/JustApp pull request #4
Opened 2023-03-13 18:52 UTC by maksontakson

2023-03-16 08:37 UTC, palyvtop requested changes

2023-03-16 08:37 UTC, palyvtop commented on ActionStorage-master/src/test/java/app/just/actionstorage/repository/AbstractTest.java
> +    registry.add("spring.datasource.url", CONTAINER::getJdbcUrl);
Check driver for db

2023-03-19 16:20 UTC, illiapal requested changes

2023-03-19 16:20 UTC, illiapal commented on ActionStorage-master/src/test/java/app/just/actionstorage/repository/AbstractTest.java
> +    registry.add("spring.datasource.password", CONTAINER::getPassword);
You can move this property in application.yaml

2023-03-20 16:51 UTC, maksontakson commented on ActionStorage-master/src/test/java/app/just/actionstorage/repository/AbstractTest.java
> +    registry.add("spring.datasource.password", CONTAINER::getPassword);
I can't then inject it to my class beacuse of static modifier and this class is not a Bean of Spring.

2023-03-20 16:55 UTC, maksontakson commented
Sorry, i had to add new commit while resolving conflicts here

2023-03-22 10:29 UTC, palyvtop approved these changes

2023-03-22 12:21 UTC, merged