MVC tests for Action Controller
maksontakson/JustApp pull request #6
Opened 2023-03-13 19:32 UTC by maksontakson

2023-03-13 19:33 UTC, maksontakson commented on ActionStorage-master/src/test/java/app/just/actionstorage/controller/ActionControllerTest.java
> +        .andExpect(status().isOk()).andExpect(content().string(containsString("test_user_first")));
Should i use here Db riders` @ExpectedDataSet instead of "test_user_first"

2023-03-16 08:40 UTC, palyvtop requested changes

2023-03-16 08:40 UTC, palyvtop commented on ActionStorage-master/src/test/java/app/just/actionstorage/controller/ActionControllerTest.java
> +        .andExpect(status().isOk()).andExpect(content().string(containsString("test_user_first")));
No, but you need make better data comparing

2023-03-16 08:40 UTC, palyvtop commented on ActionStorage-master/src/test/java/app/just/actionstorage/controller/ActionControllerTest.java
> +  private static final CreateNewActionRequestDto ACTION_REQUEST_DTO_1 =
I dont see mocked repository

2023-03-19 16:23 UTC, illiapal requested changes

2023-03-19 16:23 UTC, illiapal commented on ActionStorage-master/src/test/java/app/just/actionstorage/repository/AbstractTest.java
> +  public static void overrideProps(DynamicPropertyRegistry registry) {
You dont need this class for this task

2023-03-22 10:30 UTC, illiapal approved these changes

2023-03-22 12:05 UTC, merged